-- meta_data.lua
-- 쐐기 메타 랭킹 (murlok.io 상위 50명 기준)
-- 업데이트: 2026-04-30

ItemInfoMetaData = {
    dps = {
        {rank=1, classId="EVOKER", specIndex=3, score=3865, nameEn="Augmentation Evoker"},
        {rank=2, classId="DEMONHUNTER", specIndex=3, score=3856, nameEn="Devourer Demon Hunter"},
        {rank=3, classId="DEATHKNIGHT", specIndex=3, score=3836, nameEn="Unholy Death Knight"},
        {rank=4, classId="WARLOCK", specIndex=2, score=3835, nameEn="Demonology Warlock"},
        {rank=5, classId="PALADIN", specIndex=3, score=3808, nameEn="Retribution Paladin"},
        {rank=6, classId="WARRIOR", specIndex=1, score=3775, nameEn="Arms Warrior"},
        {rank=7, classId="DRUID", specIndex=2, score=3762, nameEn="Feral Druid"},
        {rank=8, classId="SHAMAN", specIndex=1, score=3754, nameEn="Elemental Shaman"},
        {rank=9, classId="PRIEST", specIndex=3, score=3712, nameEn="Shadow Priest"},
        {rank=10, classId="MAGE", specIndex=3, score=3709, nameEn="Frost Mage"},
        {rank=11, classId="HUNTER", specIndex=3, score=3680, nameEn="Survival Hunter"},
        {rank=12, classId="ROGUE", specIndex=1, score=3675, nameEn="Assassination Rogue"},
        {rank=13, classId="WARRIOR", specIndex=2, score=3675, nameEn="Fury Warrior"},
        {rank=14, classId="HUNTER", specIndex=1, score=3672, nameEn="Beast Mastery Hunter"},
        {rank=15, classId="DRUID", specIndex=1, score=3654, nameEn="Balance Druid"},
        {rank=16, classId="ROGUE", specIndex=2, score=3642, nameEn="Outlaw Rogue"},
        {rank=17, classId="SHAMAN", specIndex=2, score=3607, nameEn="Enhancement Shaman"},
        {rank=18, classId="ROGUE", specIndex=3, score=3606, nameEn="Subtlety Rogue"},
        {rank=19, classId="DEMONHUNTER", specIndex=1, score=3597, nameEn="Havoc Demon Hunter"},
        {rank=20, classId="MONK", specIndex=3, score=3592, nameEn="Windwalker Monk"},
        {rank=21, classId="HUNTER", specIndex=2, score=3569, nameEn="Marksmanship Hunter"},
        {rank=22, classId="MAGE", specIndex=1, score=3442, nameEn="Arcane Mage"},
        {rank=23, classId="EVOKER", specIndex=1, score=3425, nameEn="Devastation Evoker"},
        {rank=24, classId="WARLOCK", specIndex=1, score=3389, nameEn="Affliction Warlock"},
        {rank=25, classId="MAGE", specIndex=2, score=3388, nameEn="Fire Mage"},
        {rank=26, classId="WARLOCK", specIndex=3, score=3334, nameEn="Destruction Warlock"},
        {rank=27, classId="DEATHKNIGHT", specIndex=2, score=3259, nameEn="Frost Death Knight"},
    },
    healer = {
        {rank=1, classId="DRUID", specIndex=4, score=3832, nameEn="Restoration Druid"},
        {rank=2, classId="MONK", specIndex=2, score=3818, nameEn="Mistweaver Monk"},
        {rank=3, classId="SHAMAN", specIndex=3, score=3815, nameEn="Restoration Shaman"},
        {rank=4, classId="PRIEST", specIndex=1, score=3667, nameEn="Discipline Priest"},
        {rank=5, classId="PALADIN", specIndex=1, score=3664, nameEn="Holy Paladin"},
        {rank=6, classId="EVOKER", specIndex=2, score=3587, nameEn="Preservation Evoker"},
        {rank=7, classId="PRIEST", specIndex=2, score=3461, nameEn="Holy Priest"},
    },
    tank = {
        {rank=1, classId="MONK", specIndex=1, score=3881, nameEn="Brewmaster Monk"},
        {rank=2, classId="DRUID", specIndex=3, score=3682, nameEn="Guardian Druid"},
        {rank=3, classId="WARRIOR", specIndex=3, score=3644, nameEn="Protection Warrior"},
        {rank=4, classId="DEATHKNIGHT", specIndex=1, score=3632, nameEn="Blood Death Knight"},
        {rank=5, classId="PALADIN", specIndex=2, score=3594, nameEn="Protection Paladin"},
        {rank=6, classId="DEMONHUNTER", specIndex=2, score=3591, nameEn="Vengeance Demon Hunter"},
    },
}
